#FROM resin/%%RESIN_MACHINE_NAME%%-debian
#For RPi1
FROM resin/rpi-raspbian:jessie

#switch on systemd init system in container
ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential \
	wiringpi \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN g++ -o hello hello.cpp

CMD ./hello
